services:
  app:
    container_name: exchange-rate-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis:6379
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    container_name: exchange-redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
