version: '3.8'

services:
  app:
    container_name: exchange-rate-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
    restart: unless-stopped

  dynamodb-local:
    container_name: exchange-dynamo
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamo-data:/home/dynamodblocal/data
    restart: unless-stopped

volumes:
  dynamo-data:
